# Generated by Django 5.1.4 on 2025-01-18 01:02

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('picture_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.ImageField(upload_to='memories/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
