# Generated by Django 5.1.4 on 2025-01-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
