# Generated by Django 5.1.4 on 2025-01-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
