# Generated by Django 5.1.4 on 2025-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='song',
        ),
        migrations.AddField(
            model_name='guest',
            name='party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='party_only',
            field=models.BooleanField(default=False),
        ),
    ]
