# Generated by Django 5.1.4 on 2025-01-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_guest_song_guest_party_guest_party_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='attending',
            new_name='wedding',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
    ]
