# Generated by Django 5.1.4 on 2025-01-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_invitation_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='meal',
            field=models.BooleanField(default=False),
        ),
    ]
